# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: warning
  logs:
    custom_components.marstek_cloud: debug
    custom_components.renson_test: debug
    custom_components.marstek_local_api: debug

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.2      # my swag container
    - 192.168.0.1     # if my router is seen as the source

google_assistant:
  project_id: home-assistant-dc320
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true

template:
  - sensor:
        
        # =========================
        # Sensors for Easee charging
        # =========================
        
      - name: Easee Charging Mode Readonly
        state: "{{ states('input_select.easee_charging_mode') }}"
        icon: mdi:ev-station

      - name: Easee Dynamic Current Readonly
        state: "{{ states('input_number.easee_dynamic_current') | int }}"
        unit_of_measurement: "A"
        icon: mdi:current-ac

# =========================
# Helpers for Easee charging
# =========================
input_number:
  easee_dynamic_current:
    name: Easee Dynamic Current
    min: 0
    max: 32
    step: 1
    initial: 6
    unit_of_measurement: A
    icon: mdi:current-ac

input_select:
  easee_charging_mode:
    name: Easee Charging Mode
    options:
      - Default
      - Boost
      - Solar only
    icon: mdi:ev-station

# =========================
# Scripts for Easee charging
# =========================
script:
  easee_mode_default:
    alias: Easee Default
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.easee_dynamic_current
          value: 6
      - service: input_select.select_option
        data:
          entity_id: input_select.easee_charging_mode
          option: "Default"

  easee_mode_boost:
    alias: Easee Boost
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.easee_charging_mode
          option: "Boost"

  easee_mode_solar_only:
    alias: Easee Solar Only
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.easee_dynamic_current
          value: 0
      - service: input_select.select_option
        data:
          entity_id: input_select.easee_charging_mode
          option: "Solar only"